// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobirollerTestProject.DataAccess.Context;

namespace MobirollerTestProject.DataAccess.Migrations
{
    [DbContext(typeof(MobirollerContext))]
    partial class MobirollerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Cyrillic_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MobirollerTestProject.DataAccess.Models.Italian", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dc_Categoria")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dc_Categoria");

                    b.Property<string>("Dc_Evento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dc_Evento");

                    b.Property<string>("Dc_Orario")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dc_Orario");

                    b.HasKey("ID");

                    b.ToTable("Italian");
                });

            modelBuilder.Entity("MobirollerTestProject.DataAccess.Models.Turkish", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dc_Kategori")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dc_Kategori");

                    b.Property<string>("Dc_Olay")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dc_Olay");

                    b.Property<string>("Dc_Zaman")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dc_Zaman");

                    b.HasKey("ID");

                    b.ToTable("Turkish");
                });

            modelBuilder.Entity("MobirollerTestProject.DataAccess.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Password")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
